return {
  ["workshop-1207269058"]={ configuration_options={  }, enabled=true },
  ["workshop-1378549454"]={
    configuration_options={
      ["MemSpikeFix:"]=false,
      MemSpikeFixmaster_override=true,
      ["MemSpikeFixworkshop-1120124958"]="default",
      ["MemSpikeFixworkshop-1207269058"]="default",
      ["MemSpikeFixworkshop-2287303119"]="default",
      ["MemSpikeFixworkshop-2321974509"]="default",
      ["MemSpikeFixworkshop-3075429483"]="default",
      ["MemSpikeFixworkshop-345692228"]="default",
      ["MemSpikeFixworkshop-347079953"]="default",
      ["MemSpikeFixworkshop-352373173"]="default",
      ["MemSpikeFixworkshop-362175979"]="default",
      ["MemSpikeFixworkshop-374550642"]="default",
      ["MemSpikeFixworkshop-375850593"]="default",
      ["MemSpikeFixworkshop-376333686"]="default",
      ["MemSpikeFixworkshop-378160973"]="default",
      ["MemSpikeFixworkshop-458587300"]="default",
      ["MemSpikeFixworkshop-501385076"]="default",
      ["MemSpikeFixworkshop-569043634"]="default",
      ["MemSpikeFixworkshop-727774324"]="default",
      ["MemSpikeFixworkshop-758532836"]="default",
      ["MemSpikeFixworkshop-836583293"]="default",
      craftinghighlight=false 
    },
    enabled=true 
  },
  ["workshop-2287303119"]={
    configuration_options={
      [""]=0,
      Show_naughtiness=true,
      Show_range=true,
      T_crop=true,
      chestB=-1,
      chestG=-1,
      chestR=-1,
      display_hp=1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      item_info_mod=0,
      lang="auto",
      show_buddle_item=1,
      show_food_units=-1,
      show_fuel=true,
      show_fueled=3,
      show_nutrients=1,
      show_planar_resist=true,
      show_uses=-1 
    },
    enabled=true 
  },
  ["workshop-2321974509"]={ configuration_options={ SIB=false, SSB=false }, enabled=true },
  ["workshop-3075429483"]={
    configuration_options={
      ENABLEBACKPACK=false,
      ENABLEINTERSEP=15,
      INITIALSLOT=false,
      INVENTORYSIZE=45,
      MOREEQUIPSLOTS=false 
    },
    enabled=true 
  },
  ["workshop-347079953"]={
    configuration_options={ DFV_Language="EN", DFV_MinimalMode="default" },
    enabled=true 
  },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-374550642"]={
    configuration_options={
      FORCE_STACKSIZES=false,
      STACK_SIZE_LARGEITEM=40,
      STACK_SIZE_MEDITEM=80,
      STACK_SIZE_PELLET=250,
      STACK_SIZE_SMALLITEM=99,
      STACK_SIZE_TINYITEM=120 
    },
    enabled=true 
  },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-458587300"]={ configuration_options={ Ownership=false, Travel_Cost=32 }, enabled=true },
  ["workshop-501385076"]={
    configuration_options={
      quick_cook_on_fire=true,
      quick_harvest=true,
      quick_pick_cactus=true,
      quick_pick_plant_normal_ground=true 
    },
    enabled=true 
  },
  ["workshop-569043634"]={
    configuration_options={
      [""]=false,
      Health_Penalty_Campfire="Unchanged",
      Health_Penalty_Generic="Unchanged",
      Health_Penalty_Maximum="Unchanged",
      Health_Penalty_Meat_Effigy="Unchanged",
      Health_Penalty_Portal="Unchanged",
      Health_Penalty_Skeleton="Unchanged",
      Health_Respawn_Amount="Unchanged",
      KeepInventory="Unchanged",
      KeepInventory_BugFix="Unchanged",
      KillMe="Unchanged",
      NoPlayerSkeletons="Unchanged",
      RespawnMe="Unchanged",
      ReturnHotkey="Unchanged",
      ReturnHotkey_Mode="Closest",
      SpawnProtection="Unchanged",
      campfire="Enabled",
      coldfire="Enabled",
      coldfirepit="Enabled",
      firepit="Enabled",
      reviver="Unchanged",
      skeleton="Unchanged",
      usetags="Unchanged" 
    },
    enabled=true 
  },
  ["workshop-758532836"]={
    configuration_options={
      AUTOPAUSECONSOLE=false,
      AUTOPAUSEMAP=false,
      AUTOPAUSESINGLEPLAYER=true,
      ENABLECLIENTPAUSING=false,
      ENABLEHOTKEY=false,
      KEYBOARDTOGGLEKEY="P" 
    },
    enabled=true 
  } 
}